# Generated by Django 2.1.7 on 2019-03-19 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 22, 49, 341233, tzinfo=utc)),
        ),
    ]
